on:
  push:
    branches:
      - main

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nodenv/actions/setup-nodenv@v2
      - run: npm ci
      - uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
